language: csharp
stages:
  - test
  - deploy
solution: ArchUnit.sln
jobs:
  include:
    - stage: test
      mono: none
      os: linux
      script: chmod +x ./Travis/test_linux.sh && ./Travis/test_linux.sh
    - stage: test
      mono: none
      os: windows
      script: 
      - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
      - PowerShell -File Travis/test_windows.ps1
    - stage: deploy
      script: 
      - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
      - PowerShell -File deploy.ps1
      on:
        tags: true
        all_branches: true
