language: csharp
stages:
  - test
  - deploy
solution: ArchUnit.sln
jobs:
  include:
    - stage: test
      mono: none
      os: linux
      script: ./Travis/test_linux.sh
    - stage: test
      mono: none
      os: windows
      script: PowerShell -File Travis/test_windows.ps1
    - stage: deploy
      script: PowerShell -File deploy.ps1
      on:
        tags: true
        all_branches: true
