language: csharp
stages:
  - test
  - deploy
solution: ArchUnit.sln
jobs:
  include:
    - stage: test
      dotnet: 2.2.402
      mono: none
      os: linux
      script: chmod +x ./Travis/test_linux.sh && ./Travis/test_linux.sh
    - stage: test
      mono: none
      os: windows
      before_script:
        - choco install dotnetcore-sdk --version=2.2.402
        - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
      script: 
      - PowerShell -File Travis/test_windows.ps1
    - stage: deploy
      mono: none
      os: windows
      before_script:
        - choco install dotnetcore-sdk --version=2.2.402
        - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
      script:
      - PowerShell -File Travis/deploy.ps1 -tag "$TAVIS_TAG"
      on:
        tags: true
        all_branches: true
